# Generated by Django 4.0.6 on 2022-08-24 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_expense_user_remove_income_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expense',
            new_name='Expence',
        ),
    ]
